export const HS_NODE_BASE_URL = "http://192.168.43.43:5000/"
export const HS_NODE_DID_REGISTER_API = "api/did/register"
export const HS_DID_SCHEME = "did:hs"
export const SUPERHERO_HS_AUTH_BASE_URL = "http://localhost:9000/"
export const SUPERHERO_HS_AUTH_CREDENTIAL_ISSUE_API = "api/auth/register"